---
title: "Retraining and exploration of the ToBaCCo MOFs"
author: "Ben Bucior"
date: "November 9, 2017"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(stringr)

library(purrr)
library(readxl)

library(caret)
library(glmnet)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

theme_set(theme_bw(base_size=16) + theme(aspect.ratio=1))  # Default ggplot2 params
```

## Data import and processing

```{r load.data, include=FALSE}
h2_types <- paste0("h2.", c("g.L", "mol.kg", "wtp"))
tobacco_data <- read_xlsx(
  "BigData/CrystGrowthDesign_SI.xlsx",
  sheet = "data",
  skip = 3, na = "inf",
  col_names = c(
    "MOF.ID",
    "vf", "vsa", "gsa", "pld", "lcd",
    paste0(h2_types, ".100.77"),
    paste0(h2_types, ".100.130"),
    paste0(h2_types, ".100.200"),
    paste0(h2_types, ".100.243"),
    paste0("h2.qst.6.", c(77, 130, 200, 243)),
    paste0("ch4.", rep(c("v.v.", "mg.g."), 2), c("100.298", "100.298", "65.298", "65.298")),
    "ch4.qst.6.298",
    paste0("xe.kr.1.", c("xe", "kr", "select")),
    paste0("xe.kr.5.", c("xe", "kr", "select")),
    "topology",
    paste0("n1.", c("sym", "character", "ID")),
    paste0("n2.", c("sym", "character", "ID")),
    "cbb.ID"
    )
  )
tobacco_codes <- read_table2("BigData/mofs_map.dat", col_names = c("MOF.ID", "python.id"), col_types="ic")

tobacco_data <- tobacco_data %>% left_join(tobacco_codes, by="MOF.ID")

# Translate between Scotty's ID and the traditional ToBaCCo filename
scotty_codes <- read_tsv("BigData/tobacco-20171114/key.tsv", col_names = c("filename", "id"), col_types="cc")
scotty_codes <- scotty_codes %>% mutate(python.id = str_sub(filename, 1, -5))  # trim .cif suffix
tobacco_data <- tobacco_data %>% inner_join(scotty_codes, by="python.id")

DATA_SPLIT <- c(0.4, 0.4, 0.2)
R_GAS_KJ <- 8.314 / 1000
source("R/regression_and_features.R")  # Get regression utilities
```

```{r load_low_p}
# Also import the new low pressure data
low_p_h2_data <- read_tsv(
  "BigData/tobacco-20171114/clean-gcmc/comb-volume-77k.tsv",
  col_names = c("tob.num", "id", "h2.v.v.2.77", "h2.err.v.v.2.77"),  # TODO: verify that this is 2 bar, 77 K data for H2, and GCMC errors
  col_types = "icnn"
  )
low_p_h2_data <- low_p_h2_data %>% 
  mutate(`h2.g.L.2.77` = `h2.v.v.2.77` * 2.02 / 22.4) %>% 
  mutate(`h2.err.g.L.2.77` = `h2.err.v.v.2.77` * 2.02 / 22.4)
tobacco_data <- tobacco_data %>% inner_join(low_p_h2_data, by="id")  # For now, let's only import complete data
tobacco_data <- tobacco_data %>% mutate(h2.deliv.77 = h2.g.L.100.77 - h2.g.L.2.77)
```

```{r load_grids}
if (!exists("grids_h2")) {
  grids_h2 <- read_rds("BigData/Robj/tobacco_h2.Rds")
  # TODO: we should calculate the base histogram with less granularity (0.05 kJ/mol instead of 0.01) to considerably reduce file and processing size
}
```

```{r partition_data}
y_to_join <- tobacco_data %>% 
  rename(g.L = h2.deliv.77) %>% 
  select(id, g.L) %>% 
  filter(!(is.na(g.L) | g.L < 0))  # Clean up unphysical MOFs

hist_sets <- partition_data_subsets(grids_h2, y_to_join, DATA_SPLIT)
```

Long-term, we also may consider moving this to a modular, independent R script to generate the figures all separately.  (Save models as R objects and import them individually as necessary, then ggsave the plots as their publication-ready formats)

## ANALYSIS


